# Generated by Django 5.2 on 2025-04-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost', '0001_initial'),
        ('diaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celuloseVirgemCUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('gelCUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('tnt162CUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('tnt750CUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('tnt780CUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('fitaAdesivaCUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('elasticoCUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('barreiraCUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('polietileno162CUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('polietileno750CUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('polietileno780CUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('hotMeltCUT', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('fraldaCustoTotalSemPerdas', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('fraldaCustoTotalComPerdas', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('fraldaCustoPacote', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('fraldaCUF', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('precoVenda', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('precoVendaUnitario', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('precoVendaST', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('precoVendaUnitarioST', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('custoObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.cost', verbose_name='Custo')),
                ('fraldaObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaper.diaper', verbose_name='Fralda')),
            ],
        ),
    ]
