# Generated by Django 5.2 on 2025-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('ABS BELLAFRAL CONFORT', 'ABS BELLAFRAL CONFORT'), ('ABS BELLAFRAL BASIC', 'ABS BELLAFRAL BASIC'), ('ABS BIG CONFORT', 'ABS BIG CONFORT'), ('FRALDA BELLAFRAL CONFORT', 'FRALDA BELLAFRAL CONFORT'), ('FRALDA BELLAFRAL BASIC', 'FRALDA BELLAFRAL BASIC'), ('FRALDA BIG CONFORT', 'FRALDA BIG CONFORT')], max_length=100, verbose_name='Modelo')),
                ('identificador', models.CharField(max_length=100, verbose_name='Identificador')),
                ('tamanho', models.CharField(choices=[('XG', 'XG'), ('G', 'G'), ('M', 'M'), ('TAMANHO ÚNICO', 'TAMANHO ÚNICO')], max_length=100, verbose_name='Tamanho')),
                ('qtdCeluloseVirgem', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Celulose virgem (Kg)')),
                ('qtdGel', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Gel (Kg)')),
                ('qtdTnt162', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT 162 (m2)')),
                ('qtdTnt750', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 750 (m2)')),
                ('qtdTnt780', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 780 (m2)')),
                ('qtdFitaAdesiva', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Fita adesiva (m)')),
                ('qtdElastico', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Elastico (Kg)')),
                ('qtdBarreira', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Barreira (m2)')),
                ('qtdPolietileno162', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 162 (Kg)')),
                ('qtdPolietileno750', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 750 (Kg)')),
                ('qtdPolietileno780', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Polietileno 780 (Kg)')),
                ('qtdHotMelt', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Hot-Melt (Kg)')),
                ('qtdPorPacote', models.IntegerField(verbose_name='Quantidade de fraldas por pacote')),
                ('percentPerdas', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Perdas (%)')),
                ('precoEmbalagem', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Embalagem (R$)')),
                ('precoFardoEncarte', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Saco para fardos/Encarte (R$)')),
                ('percentComissao', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Comissão (%)')),
                ('percentImpostos', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Impostos (%)')),
                ('percentFrete', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Frete (%)')),
                ('percentMargem', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Margem de contribuição (%)')),
                ('percentST', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ST (%)')),
            ],
        ),
    ]
