# Generated by Django 5.2 on 2025-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('custoCeluloseVirgem', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Celulose virgem (R$)')),
                ('custoGel', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Gel (R$)')),
                ('custoTnt162', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT 162 (R$)')),
                ('custoTnt750', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 750 (R$)')),
                ('custoTnt780', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TNT 780 (R$)')),
                ('custoFitaAdesiva', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Fita adesiva (R$)')),
                ('custoElastico', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Elastico (R$)')),
                ('custoBarreira', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Barreira (R$)')),
                ('custoPolietileno162', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 162 (R$)')),
                ('custoPolietileno750', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno 750 (R$)')),
                ('custoPolietileno780', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Polietileno 780 (R$)')),
                ('custoHotMelt', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Hot-Melt (R$)')),
            ],
        ),
    ]
